version: '3.7'

services:

  setup:
    profiles:
      - setup
    build:
      context: elkstack/setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    network_mode: host
    volumes:
      - ./elkstack/setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./elkstack/setup/lib.sh:/lib.sh:ro,Z
      - ./elkstack/setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  back:
    image: iadopt/aitwork-back:0.1.1
    container_name: aitwork-back
    depends_on:
      - mongodb
      - minio
      - elasticsearch
    restart: unless-stopped
    network_mode: host
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      COHERE_API_KEY: ${COHERE_API_KEY:-}
      REPLICATE_API_TOKEN: ${REPLICATE_API_TOKEN:-}
      CLIENT_JWT_SECRET: ${CLIENT_JWT_SECRET:-}
      WEBSITE_JWT_SECRET: ${WEBSITE_JWT_SECRET:-}
      WEBSITE_URL: ${WEBSITE_URL:-}
      MONGODB_URL: ${MONGODB_URL:-}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL:-}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD:-}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-}
      MINIO_BUCKET: ${MINIO_BUCKET:-}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-}
    volumes:
      - public_back_data:/tmp/uploads

  front:
    build:
      context: front/
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: aitwork-front
    network_mode: host
    restart: unless-stopped
    depends_on:
      - back

  mongodb:
    image: mongo:6.0
    container_name: public-mongodb
    restart: unless-stopped
    network_mode: host
    volumes:
      - public_mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: public-mongo-express
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_PORT: ${ME_CONFIG_MONGODB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

  minio:
    image:  quay.io/minio/minio:latest
    container_name: client-minio
    network_mode: host
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-}
      TZ: Europe/Paris
    command: server /data --console-address :9001
    volumes:
      - public_minio_data:/data

  elasticsearch:
    container_name: public-elasticsearch
    image: elasticsearch:8.11.3
    network_mode: host
    volumes:
      - ./elkstack/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - public_elasticsearch_data:/usr/share/elasticsearch/data:Z
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    restart: unless-stopped

  logstash:
    container_name: public-logstash
    network_mode: host
    image: logstash:8.11.3
    volumes:
      - ./elkstack/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./elkstack/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    container_name: public-kibana
    network_mode: host
    image: kibana:8.11.3
    volumes:
      - ./elkstack/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    depends_on:
      - elasticsearch
    restart: unless-stopped


volumes:
  public_back_data:
  public_elasticsearch_data:
  public_minio_data:
  public_mongodb_data: