apiVersion: 1

datasources:
- name: Elasticsearch-logs
  type: elasticsearch
  access: proxy
  url: http://elasticsearch:${ELASTICSEARCH_PORT}
  isDefault: false
  basicAuth: true
  basicAuthUser: elastic
  basicAuthPassword: ${ELASTIC_PASSWORD}
  jsonData:
    timeField: "@timestamp"
  version: 10
